// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Netcrave.ifconfig.me.schema {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class info {
        
        private string charsetField;
        
        private string connectionField;
        
        private string encodingField;
        
        private string forwardedField;
        
        private string ip_addrField;
        
        private string keep_aliveField;
        
        private string langField;
        
        private string mimeField;
        
        private int portField;
        
        private string remote_hostField;
        
        private string user_agentField;
        
        private string viaField;
        
        /// <remarks/>
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
            }
        }
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        public string forwarded {
            get {
                return this.forwardedField;
            }
            set {
                this.forwardedField = value;
            }
        }
        
        /// <remarks/>
        public string ip_addr {
            get {
                return this.ip_addrField;
            }
            set {
                this.ip_addrField = value;
            }
        }
        
        /// <remarks/>
        public string keep_alive {
            get {
                return this.keep_aliveField;
            }
            set {
                this.keep_aliveField = value;
            }
        }
        
        /// <remarks/>
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string mime {
            get {
                return this.mimeField;
            }
            set {
                this.mimeField = value;
            }
        }
        
        /// <remarks/>
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string remote_host {
            get {
                return this.remote_hostField;
            }
            set {
                this.remote_hostField = value;
            }
        }
        
        /// <remarks/>
        public string user_agent {
            get {
                return this.user_agentField;
            }
            set {
                this.user_agentField = value;
            }
        }
        
        /// <remarks/>
        public string via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
    }
}
